all: build compress

changeLangFile:
	cp -f ./langs/zh_cn-yun.json ./src/langs/zh_cn.json && \
	cp -f ./langs/en-yun.json ./src/langs/en.json


compress:
	cd dist && \
	zip -r obsidian-ydcpub.zip obsidian-ydcpub && \
	shasum -a 256 obsidian-ydcpub.zip > obsidian-ydcpub.sha256sum

build: changeLangFile
	yarn && \
	yarn build && \
	cd dist && \
	mkdir -p obsidian-ydcpub && \
	mv -f ./main.js obsidian-ydcpub/main.js && \
	mv -f ./manifest.json obsidian-ydcpub/manifest.json && \
	mv -f ./styles.css obsidian-ydcpub/styles.css

dev: changeLangFile
	yarn && \
	yarn dev && \
	cd dist && \
	mkdir -p obsidian-ydcpub && \
	mv -f ./main.js obsidian-ydcpub/main.js && \
	mv -f ./manifest.json obsidian-ydcpub/manifest.json && \
	mv -f ./styles.css obsidian-ydcpub/styles.css

clean:
	rm -rf dist/*
	
install: dev
	mkdir -p /g/obsidianVaults/build_dev_new/.obsidian/plugins/obsidian-ydcpub && \
	cp -f ./dist/obsidian-ydcpub/main.js /g/obsidianVaults/build_dev_new/.obsidian/plugins/obsidian-ydcpub/main.js && \
	cp -f ./dist/obsidian-ydcpub/manifest.json /g/obsidianVaults/build_dev_new/.obsidian/plugins/obsidian-ydcpub/manifest.json && \
	cp -f ./dist/obsidian-ydcpub/styles.css  /g/obsidianVaults/build_dev_new/.obsidian/plugins/obsidian-ydcpub/styles.css

install-1: dev
	mkdir -p /g/obsidianVaults/build_dev/.obsidian/plugins/obsidian-ydcpub && \
	cp -f ./dist/obsidian-ydcpub/main.js /g/obsidianVaults/build_dev/.obsidian/plugins/obsidian-ydcpub/main.js && \
	cp -f ./dist/obsidian-ydcpub/manifest.json /g/obsidianVaults/build_dev/.obsidian/plugins/obsidian-ydcpub/manifest.json && \
	cp -f ./dist/obsidian-ydcpub/styles.css  /g/obsidianVaults/build_dev/.obsidian/plugins/obsidian-ydcpub/styles.css

install-back: dev
	mkdir -p /g/obsidianVaults/pv_back_dev/.obsidian/plugins/obsidian-ydcpub && \
	cp -f ./dist/obsidian-ydcpub/main.js /g/obsidianVaults/pv_back_dev/.obsidian/plugins/obsidian-ydcpub/main.js && \
	cp -f ./dist/obsidian-ydcpub/manifest.json /g/obsidianVaults/pv_back_dev/.obsidian/plugins/obsidian-ydcpub/manifest.json && \
	cp -f ./dist/obsidian-ydcpub/styles.css  /g/obsidianVaults/pv_back_dev/.obsidian/plugins/obsidian-ydcpub/styles.css

install-2: dev
	mkdir -p /g/obsidianVaults/build_dev_new/.obsidian/plugins/obsidian-ydcpub && \
	cp -f ./dist/obsidian-ydcpub/main.js  /g/obsidianVaults/build_dev_new/.obsidian/plugins/obsidian-ydcpub/main.js && \
	cp -f ./dist/obsidian-ydcpub/manifest.json  /g/obsidianVaults/build_dev_new/.obsidian/plugins/obsidian-ydcpub/manifest.json
	cp -f ./dist/obsidian-ydcpub/styles.css  /g/obsidianVaults/build_dev_new/.obsidian/plugins/obsidian-ydcpub/styles.css

.PHONY: all changeLangFile dev build compress clean install install-1 install-back
