all: build compress

changeLangFile:
	cp -f ./langs/zh_cn-saas.json ./src/langs/zh_cn.json && \
	cp -f ./langs/en-saas.json ./src/langs/en.json

compress:
	cd dist && \
	zip -r obsidian-ydcpub-saas.zip obsidian-ydcpub-saas && \
	shasum -a 256 obsidian-ydcpub-saas.zip > obsidian-ydcpub-saas.sha256sum

build: changeLangFile
	yarn && \
	yarn buildSaaS && \
	cd dist && \
	mkdir -p obsidian-ydcpub-saas && \
	mv -f ./main.js obsidian-ydcpub-saas/main.js && \
	mv -f ./manifest.json obsidian-ydcpub-saas/manifest.json && \
	mv -f ./styles.css obsidian-ydcpub-saas/styles.css

dev: changeLangFile
	yarn && \
	yarn devSaaS && \
	cd dist && \
	mkdir -p obsidian-ydcpub-saas && \
	mv -f ./main.js obsidian-ydcpub-saas/main.js && \
	mv -f ./manifest.json obsidian-ydcpub-saas/manifest.json && \
	mv -f ./styles.css obsidian-ydcpub-saas/styles.css

clean:
	rm -rf dist/*
	
install: dev
	mkdir -p /g/obsidianVaults/plugin_dev_new/.obsidian/plugins/obsidian-ydcpub-saas && \
	cp -f ./dist/obsidian-ydcpub-saas/main.js  /g/obsidianVaults/plugin_dev_new/.obsidian/plugins/obsidian-ydcpub-saas/main.js && \
	cp -f ./dist/obsidian-ydcpub-saas/manifest.json  /g/obsidianVaults/plugin_dev_new/.obsidian/plugins/obsidian-ydcpub-saas/manifest.json
	cp -f ./dist/obsidian-ydcpub-saas/styles.css  /g/obsidianVaults/plugin_dev_new/.obsidian/plugins/obsidian-ydcpub-saas/styles.css
install-1: dev
	mkdir -p /g/obsidianVaults/plugin_dev/.obsidian/plugins/obsidian-ydcpub-saas && \
	cp -f ./dist/obsidian-ydcpub-saas/main.js  /g/obsidianVaults/plugin_dev/.obsidian/plugins/obsidian-ydcpub-saas/main.js && \
	cp -f ./dist/obsidian-ydcpub-saas/manifest.json  /g/obsidianVaults/plugin_dev/.obsidian/plugins/obsidian-ydcpub-saas/manifest.json
	cp -f ./dist/obsidian-ydcpub-saas/styles.css  /g/obsidianVaults/plugin_dev/.obsidian/plugins/obsidian-ydcpub-saas/styles.css
install-2: dev
	mkdir -p /g/obsidianVaults/niu_dev/.obsidian/plugins/obsidian-ydcpub-saas && \
	cp -f ./dist/obsidian-ydcpub-saas/main.js  /g/obsidianVaults/niu_dev/.obsidian/plugins/obsidian-ydcpub-saas/main.js && \
	cp -f ./dist/obsidian-ydcpub-saas/manifest.json  /g/obsidianVaults/niu_dev/.obsidian/plugins/obsidian-ydcpub-saas/manifest.json
	cp -f ./dist/obsidian-ydcpub-saas/styles.css  /g/obsidianVaults/niu_dev/.obsidian/plugins/obsidian-ydcpub-saas/styles.css

.PHONY: all changeLangFile dev build compress clean install install-1 install-2
